### ISSUE TITLE
Not responsive when spinning complex strings

### ISSUE THREAD

**Issue by richshakespeare** [maximeg/content_spinning#2]
Thanks for this gem, it's a great fit for one of our projects :)

We are having an issue however when we spin strings with lots of content variations. We came across this when we tried a string with 20+ distinct {...} tags. I dug into it and found it's because the call to product is creating over 1,000,000 distinct variations. I guess this is inevitable if the gem is to create all possible variations and allow the consumer to pick one or more of these, but it does mean that complex strings are unworkable. This particular string took over 20 seconds to process and a lot of memory.

One possible solution is to add a new parameter on the spin call which limits the number of variations returned. This could then be implemented to not use 'product' or similar Ruby array functions which return all variations, but instead just generate a set number of possibilities and return these.

I'd be happy to try and PR something down the line, just wanted to check this is sensible and you'd accept a patch along these lines?

Cheers!

**Comment by maximeg** [comment]
Hi @richshakespeare ,

Thanks for using it.

It's been a long time that I wanted to rewrote it to have a more decent parser that serializes the source into a set of ruby object.
This allows us to : 
- clean the source more properly
- count the possibilities logically
- get random spins

I did it and released a 0.3.0 version.
See the readme for updated usage: https://github.com/maximeg/content_spinning#partial-spins

cheers,

**Comment by richshakespeare** [comment]
Thanks @maximeg, this looks great! Really impressed at how quickly you got this out :)
